// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sorte.console;

namespace sorte.console.Migrations
{
    [DbContext(typeof(SorteContext))]
    [Migration("20200713220734_CreateSorteDB")]
    partial class CreateSorteDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sorte.console.Megasena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Concurso")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConcurso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Megasenas");
                });

            modelBuilder.Entity("sorte.console.Sorteados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MegaSenaId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MegaSenaId");

                    b.ToTable("Sorteados");
                });

            modelBuilder.Entity("sorte.console.Sorteados", b =>
                {
                    b.HasOne("sorte.console.Megasena", "MegaSena")
                        .WithMany("NumerosSorteados")
                        .HasForeignKey("MegaSenaId");
                });
#pragma warning restore 612, 618
        }
    }
}
