// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sorte.console;

namespace sorte.console.Migrations
{
    [DbContext(typeof(SorteContext))]
    partial class SorteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sorte.console.Megasena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acumulado")
                        .HasColumnType("char(3)");

                    b.Property<double>("AcumuladoVirada")
                        .HasColumnType("float");

                    b.Property<double>("ArredacaoTotal")
                        .HasColumnType("float");

                    b.Property<int>("Concurso")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConcurso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<double>("EstimativaPremio")
                        .HasColumnType("float");

                    b.Property<int>("Ganhadores")
                        .HasColumnType("int");

                    b.Property<int>("GanhadoresQuadra")
                        .HasColumnType("int");

                    b.Property<int>("GanhadoresQuina")
                        .HasColumnType("int");

                    b.Property<double>("Rateio")
                        .HasColumnType("float");

                    b.Property<double>("RateioQuadra")
                        .HasColumnType("float");

                    b.Property<double>("RateioQuina")
                        .HasColumnType("float");

                    b.Property<double>("ValorAcumulado")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Megasenas");
                });

            modelBuilder.Entity("sorte.console.MegasenaCidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MegasenaId")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .HasColumnType("char(2)");

                    b.HasKey("Id");

                    b.HasIndex("MegasenaId");

                    b.ToTable("MegasenaCidades");
                });

            modelBuilder.Entity("sorte.console.Sorteados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MegaSenaId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MegaSenaId");

                    b.ToTable("Sorteados");
                });

            modelBuilder.Entity("sorte.console.MegasenaCidade", b =>
                {
                    b.HasOne("sorte.console.Megasena", "MegasenaConcurso")
                        .WithMany("Cidades")
                        .HasForeignKey("MegasenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sorte.console.Sorteados", b =>
                {
                    b.HasOne("sorte.console.Megasena", "MegaSena")
                        .WithMany("NumerosSorteados")
                        .HasForeignKey("MegaSenaId");
                });
#pragma warning restore 612, 618
        }
    }
}
